#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: Merge-upstream

on:
  schedule:
    - cron: 30 19 * * *
  # push:
  #   branches: 
  #     - master

jobs:

  merge:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@master
      with:
        ref: master
        fetch-depth: 0
        lfs: true

    - name: Set git identity
      run : |
        git config --global user.email "07132041@stu.xupt.edu.cn"
        git config --global user.name "Narzignaw"

    - name: Load upstream commits
      run: git pull https://github.com/KFERMercer/OpenWrt.git --no-edit

    - name: Push Commits
      env:
        DOWNSTREAM_BRANCH: master
      run: git push origin $DOWNSTREAM_BRANCH
